## Python Implementation

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math

In [56]:
df = pd.read_table("fruit_data_with_colors.txt")
df

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [57]:
df.head()

   fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [58]:
df.shape

(59, 7)

In [59]:
df.describe()

       fruit_label        mass      width     height  color_score
count    59.000000   59.000000  59.000000  59.000000    59.000000
mean      2.542373  163.118644   7.105085   7.693220     0.762881
std       1.208048   55.018832   0.816938   1.361017     0.076857
min       1.000000   76.000000   5.800000   4.000000     0.550000
25%       1.000000  140.000000   6.600000   7.200000     0.720000
50%       3.000000  158.000000   7.200000   7.600000     0.750000
75%       4.000000  177.000000   7.500000   8.200000     0.810000
max       4.000000  362.000000   9.600000  10.500000     0.930000

In [60]:
labels = dict(zip(df.fruit_label.unique(), df.fruit_name.unique())) 
labels

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}

In [61]:
df['fruit_name'].value_counts()

apple       19
orange      19
lemon       16
mandarin     5
Name: fruit_name, dtype: int64

In [62]:
df['fruit_label'].value_counts()

1    19
3    19
4    16
2     5
Name: fruit_label, dtype: int64

In [63]:
#taking random record and storing in xq
#xq = df.sample()

In [64]:
# droping the xq from data using index value
#df.drop(xq.index, inplace=True)

In [65]:
df.shape

(59, 7)

In [76]:
list1 = ['mass', 'width', 'height', 'color_score']
test_point = pd.DataFrame([[300,8.0,7.1,0.9]], columns=list1)
test_point
#test_point = pd.DataFrame(xq[['mass', 'width', 'height', 'color_score']])
#xq_final

   mass  width  height  color_score
0   300    8.0     7.1          0.9

In [77]:
# calculating ecludian distance
def cal_distance(x):      
    a = x.to_numpy()
    b = test_point.to_numpy()    
    distance = math.sqrt(sum([(a - b) ** 2 for a, b in zip(a, b[0])]))
    return distance

In [78]:
# calculating distance
df['distance'] = df[['mass', 'width', 'height', 'color_score']].apply(cal_distance, axis=1)
df

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score,distance
0,1,apple,granny_smith,192,8.4,7.3,0.55,108.001493
1,1,apple,granny_smith,180,8.0,6.8,0.59,120.000775
2,1,apple,granny_smith,176,7.4,7.2,0.60,124.001855
3,2,mandarin,mandarin,86,6.2,4.7,0.80,214.021050
4,2,mandarin,mandarin,84,6.0,4.6,0.79,216.023754
5,2,mandarin,mandarin,80,5.8,4.3,0.77,220.028855
6,2,mandarin,mandarin,80,5.9,4.3,0.81,220.027858
7,2,mandarin,mandarin,76,5.8,4.0,0.81,224.032270
8,1,apple,braeburn,178,7.1,7.8,0.92,122.005329
9,1,apple,braeburn,172,7.4,7.0,0.89,128.001446
10,1,apple,braeburn,166,6.9,7.3,0.93,134.004667
11,1,apple,braeburn,172,7.1,7.6,0.92,128.004142
12,1,apple,braeburn,154,7.0,7.1,0.88,146.003426
13,1,apple,golden_delicious,164,7.3,7.7,0.70,136.003272
14,1,apple,golden_delicious,152,7.6,7.3,0.69,148.000825
15,1,apple,golden_delicious,156,7.7,7.1,0.69,144.000466
16,1,apple,golden_delicious,156,7.6,7.5,0.67,144.001295
17,1,apple,golden_delicious,168,7.5,7.6,0.73,132.002003
18,1,apple,cripps_pink,162,7.5,7.1,0.83,138.000924
19,1,apple,cripps_pink,162,7.4,7.2,0.85,138.001350
20,1,apple,cripps_pink,160,7.5,7.5,0.86,140.001470
21,1,apple,cripps_pink,156,7.4,7.4,0.84,144.001575
22,1,apple,cripps_pink,140,7.3,7.1,0.87,160.001534
23,1,apple,cripps_pink,170,7.6,7.9,0.88,130.003078
24,3,orange,spanish_jumbo,342,9.0,9.4,0.75,42.075082
25,3,orange,spanish_jumbo,356,9.2,9.2,0.75,56.052409
26,3,orange,spanish_jumbo,362,9.6,9.2,0.74,62.056390
27,3,orange,selected_seconds,204,7.5,9.2,0.77,96.024356
28,3,orange,selected_seconds,140,6.7,7.1,0.72,160.005382
29,3,orange,selected_seconds,160,7.0,7.4,0.81,140.003922
30,3,orange,selected_seconds,158,7.1,7.5,0.79,142.003458
31,3,orange,selected_seconds,210,7.8,8.0,0.82,90.004758
32,3,orange,selected_seconds,164,7.2,7.0,0.80,136.002426
33,3,orange,turkey_navel,190,7.5,8.1,0.74,110.005798
34,3,orange,turkey_navel,142,7.6,7.8,0.75,158.002128
35,3,orange,turkey_navel,150,7.1,7.9,0.75,150.004908
36,3,orange,turkey_navel,160,7.1,7.6,0.76,140.003856
37,3,orange,turkey_navel,154,7.3,7.3,0.79,146.001856
38,3,orange,turkey_navel,158,7.2,7.8,0.77,142.004038
39,3,orange,turkey_navel,144,6.8,7.4,0.75,156.004976
40,3,orange,turkey_navel,154,7.1,7.5,0.78,146.003371
41,3,orange,turkey_navel,180,7.6,8.2,0.79,120.005759
42,3,orange,turkey_navel,154,7.2,7.2,0.82,146.002248
43,4,lemon,spanish_belsan,194,7.2,10.3,0.70,106.051497
44,4,lemon,spanish_belsan,200,7.3,10.5,0.72,100.060394
45,4,lemon,spanish_belsan,186,7.2,9.2,0.72,114.022289
46,4,lemon,spanish_belsan,216,7.3,10.2,0.71,84.060312
47,4,lemon,spanish_belsan,196,7.3,9.7,0.72,104.035006
48,4,lemon,spanish_belsan,174,7.3,10.1,0.72,126.037782
49,4,lemon,unknown,132,5.8,8.7,0.73,168.022108
50,4,lemon,unknown,130,6.0,8.2,0.71,170.015429
51,4,lemon,unknown,116,6.0,7.5,0.72,184.011392
52,4,lemon,unknown,118,5.9,8.0,0.72,182.014429
53,4,lemon,unknown,120,6.0,8.4,0.74,180.015876
54,4,lemon,unknown,116,6.1,8.5,0.71,184.015233
55,4,lemon,unknown,116,6.3,7.7,0.72,184.008919
56,4,lemon,unknown,116,5.9,8.1,0.73,184.014779
57,4,lemon,unknown,152,6.5,8.5,0.72,148.014332
58,4,lemon,unknown,118,6.1,8.1,0.70,182.012774

In [79]:
#sorting the values based on distance
df_sort = df.sort_values('distance',ascending=True)

In [80]:
# taking top 3 records because k is 3
df_after_sort = df_sort.head(3)

In [81]:
df_after_sort.reset_index()

,index,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score,distance
0,24,3,orange,spanish_jumbo,342,9.0,9.4,0.75,42.075082
1,25,3,orange,spanish_jumbo,356,9.2,9.2,0.75,56.052409
2,26,3,orange,spanish_jumbo,362,9.6,9.2,0.74,62.056390

In [82]:
df_after_sort.iloc[0]

fruit_label                  3
fruit_name              orange
fruit_subtype    spanish_jumbo
mass                       342
width                      9.0
height                     9.4
color_score               0.75
distance             42.075082
Name: 24, dtype: object

In [83]:
count = [0 for i in range(0, len(df['fruit_label'].unique()))]
for xi in range(0, len(df_after_sort)):       
    if df_after_sort.iloc[xi]['fruit_label'] == 1:        
        count[0] = count[0]+1
    elif df_after_sort.iloc[xi]['fruit_label'] == 2:        
        count[1] = count[1]+1
    elif df_after_sort.iloc[xi]['fruit_label'] == 3:        
        count[2] = count[2]+1
    elif df_after_sort.iloc[xi]['fruit_label'] == 4:        
        count[3] = count[3]+1

In [84]:
def max_num_in_list_label(list):
    maxpos = list.index(max(list)) +1
    return labels[maxpos]

In [85]:
#getting the label and verifying with the class label in xq
print(max_num_in_list_label(count))
#if max_num_in_list_label(count) in xq.values:
    #print("success")
#else:
    #print("not success")

orange

## sklearn Implementation

In [91]:
X= df[['mass', 'width', 'height', 'color_score']]
Y= df[['fruit_name']]

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, Y)

C:\Users\Home\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [93]:
predicted= neigh.predict([[300,8.0,7.1,0.9]]) # 0:Overcast, 2:Mild
print(predicted)

['orange']

C:\Users\Home\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(